version: "2"
linters:
  enable:
    - errcheck
    - errorlint
    - exhaustive
    - govet
    - gosimple
    - goimports
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused
